layout_spectrum: 0.05902192
color:
  saturation: 0.09009151
  lightness: 0.4801685
  brandStrength: 0.6254471
  brandColors:
    - '#7EB6CF'
    - '#FFFFFF'
    - '#D2E5ED'
    - '#B3B2A7'
    - '#587D8D'
  rhythmicContrast: 0.9700401
typography_spectrum: 0.3372681
name: Mu-Dar
